name: Run Auto Sign 

on:
  workflow_dispatch:
  schedule:
    # UTC time
    - cron: "0 0 * * *"

env:
  SM_USERNAME: 13701625626
  SM_PASSWORD: erzhi6162823.
      
    
    
      
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          npm install
      - name: Run 
        id: run
        run: |
          node main.js 
